-- Migration: Create vendor_uploads Storage Bucket

INSERT INTO storage.buckets (id, name, public)
VALUES ('vendor_uploads', 'vendor_uploads', false)
ON CONFLICT (id) DO NOTHING;

-- RLS Policies for vendor_uploads
-- (idempotent: re-push / remote may already have this policy)

DROP POLICY IF EXISTS "Service Role Full Access" ON storage.objects;

-- 1. Allow service_role full access
CREATE POLICY "Service Role Full Access"
ON storage.objects
FOR ALL
TO service_role
USING (bucket_id = 'vendor_uploads')
WITH CHECK (bucket_id = 'vendor_uploads');

-- Note: Vendor uploads from the portal are done via pre-signed URLs generated by the service_role.
-- Therefore, we don't strictly need public or authenticated policies for the initial upload or download.
